site_name: Food Finder
site_author: Joao Romero
site_description: Documentação Food Finder

repo_url: https://github.com/JoaoVictorRomero/ff-docs
# repo_name: foodfinder/docs
edit_uri: edit/main/docs/
# theme:
# theme:
#   features:
#     - content.action.edit
# theme:
#   icon:
#     edit: material/pencil 
#     view: material/eye

theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate
    primary: light blue


  features:
    - navigation.sections
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: material/passport-alert
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


extra_css:
  - stylesheets/extra.css

nav:
  - Instalação: "index.md"
  - Contribuição Docs: 'contribuicao-docs.md'
  - Sobre: 'sobre.md'

  - Frontend:
    - HomePage: 'homepage.md'
    - SearchPage: 'searchpage.md'
    - Admin page: 'admin.md'
    - Cadastro page: 'cadastro.md'

  - Backend:
    - Servidor Flask: 'server.md'
    - Considerações Avançadas: 'seguranca.md'

  


