site_name: Food Finder
site_author: Joao Romero
site_description: Documentação Food Finder

repo_url: https://github.com/JoaoVictorRomero/ff-docs
# repo_name: foodfinder/docs
edit_uri: edit/main/docs/
# theme:
# theme:
#   features:
#     - content.action.edit
# theme:
#   icon:
#     edit: material/pencil 
#     view: material/eye

theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate
    primary: light blue

  features:
    - navigation.sections
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: "index.md"

  - Frontend:
    - HomePage: 'homepage.md'

  - Backend:
    - SLA: 'a.md'

  - Outros:
    - Contribuição Docs: 'contribuicao-docs.md'


